export const LOAD_ADVERTISEMENT_ATTACHMENTS = 'VLAB/Advertisement/LOAD_ADVERTISEMENT_ATTACHMENTS';
export const LOAD_ADVERTISEMENT_ATTACHMENTS_SUCCESS = 'VLAB/Advertisement/LOAD_ADVERTISEMENT_ATTACHMENTS_SUCCESS';
export const LOAD_ADVERTISEMENT_ATTACHMENTS_ERROR = 'VLAB/Advertisement/LOAD_ADVERTISEMENT_ATTACHMENTS_ERROR';
export const LOAD_ADVERTISEMENT_PAGE = 'VLAB/Advertisement/LOAD_ADVERTISEMENT_PAGE';
export const LOAD_ADVERTISEMENT_PAGE_SUCCESS = 'VLAB/Advertisement/LOAD_ADVERTISEMENT_PAGE_SUCCESS';
export const LOAD_ADVERTISEMENT_PAGE_ERROR = 'VLAB/Advertisement/LOAD_ADVERTISEMENT_PAGE_ERROR';
